config/routes.rb
Recipereminder::Application.routes.draw do
  resources :recipes

  resources :user_recipes

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root :to => 'devise/registrations#edit', as: :authenticated_user_path
    end  

    root :to => 'devise/registrations#new', as: :new_user_path
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_recipe.rb
class UserRecipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description)
    end
end

app/controllers/user_recipes_controller.rb
class UserRecipesController < ApplicationController
  before_action :set_user_recipe, only: [:show, :edit, :update, :destroy]

  # GET /user_recipes
  # GET /user_recipes.json
  def index
    @user_recipes = UserRecipe.all
  end

  # GET /user_recipes/1
  # GET /user_recipes/1.json
  def show
  end

  # GET /user_recipes/new
  def new
    @user_recipe = UserRecipe.new
  end

  # GET /user_recipes/1/edit
  def edit
  end

  # POST /user_recipes
  # POST /user_recipes.json
  def create
    @user_recipe = UserRecipe.new(user_recipe_params)

    respond_to do |format|
      if @user_recipe.save
        format.html { redirect_to @user_recipe, notice: 'User recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_recipes/1
  # PATCH/PUT /user_recipes/1.json
  def update
    respond_to do |format|
      if @user_recipe.update(user_recipe_params)
        format.html { redirect_to @user_recipe, notice: 'User recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_recipes/1
  # DELETE /user_recipes/1.json
  def destroy
    @user_recipe.destroy
    respond_to do |format|
      format.html { redirect_to user_recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_recipe
      @user_recipe = UserRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_recipe_params
      params.require(:user_recipe).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/user_recipes_helper.rb
module UserRecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipereminder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	Hello user. <%= link_to "Account Info", edit_user_registration_path %>
<%  else %>
	<%= link_to "Register", new_user_registration_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.description %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/user_recipes/_form.html.erb
<%= form_for(@user_recipe) do |f| %>
  <% if @user_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_recipe.errors.count, "error") %> prohibited this user_recipe from being saved:</h2>

      <ul>
      <% @user_recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_recipes/edit.html.erb
<h1>Editing user_recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_recipe %> |
<%= link_to 'Back', user_recipes_path %>

app/views/user_recipes/index.html.erb
<h1>Listing user_recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_recipes.each do |user_recipe| %>
      <tr>
        <td><%= user_recipe.name %></td>
        <td><%= user_recipe.description %></td>
        <td><%= link_to 'Show', user_recipe %></td>
        <td><%= link_to 'Edit', edit_user_recipe_path(user_recipe) %></td>
        <td><%= link_to 'Destroy', user_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User recipe', new_user_recipe_path %>

app/views/user_recipes/new.html.erb
<h1>New user_recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', user_recipes_path %>

app/views/user_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user_recipe.description %>
</p>

<%= link_to 'Edit', edit_user_recipe_path(@user_recipe) %> |
<%= link_to 'Back', user_recipes_path %>